language: node_js
node_js:
- '10'
- '12'
- 'node'
os: linux
cache:
  directories:
  - node_modules
script: xvfb-run npm test -- --browsers ChromeHeadlessWithoutAutoplayPolicy --single-run
deploy:
  provider: npm
  email: irfs@bbc.co.uk
  api_token:
    secure: "QRQt729opZcpIORHT1yxYjUH42ClzCTJYZJkAeEHFBkOVsEntStDw+cqsCeLZoc26qlkKJKOheMfM30ZMpMTIZTweQyFpEYNmmxp1uJEsHA8NacZC66+1jq4fVXBQ/lB2HT8Sq4kz1fxnYXiiSXR13aC5VEoeHtj8g2N8CytqOo="
  on:
    tags: true
    repo: bbc/peaks.js
    node_js: 'node'
